name: Build and Push Microservices

on:
  push:
    branches: [ main ]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v3

      - name: Set up JDK 17
        uses: actions/setup-java@v3
        with:
          java-version: '17'
          distribution: 'temurin'

      # Build all microservices
      - name: Build all microservices
        run: |
          for dir in api-gateway user-service product-service order-service payment-service discovery-server
          do
            echo "Building $dir"
            mvn -f $dir/pom.xml clean package -DskipTests
          done

      - name: Log in to Docker Hub
        uses: docker/login-action@v2
        with:
          username: ${{ secrets.DOCKER_HUB_USERNAME }}
          password: ${{ secrets.DOCKER_HUB_ACCESS_TOKEN }}

      # Build and push Docker images for each service
      - name: Build & Push Docker Images
        run: |
          for dir in api-gateway user-service product-service order-service payment-service discovery-server
          do
            IMAGE_NAME="${{ secrets.DOCKER_HUB_USERNAME }}"/"$dir":latest
            echo "Building & pushing $IMAGE_NAME"

            docker build -t $IMAGE_NAME $dir
            docker push $IMAGE_NAME
          done
