name: Build and Push Microservices

on:
  push:
    branches: [ main ]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v3

      - name: Set up JDK 17
        uses: actions/setup-java@v3
        with:
          java-version: '17'
          distribution: 'temurin'

      # Loop through all service folders and build them
      - name: Build all microservices
        run: |
          for dir in api-gateway user-service product-service order-service payment-service discovery-server
          do
            echo "Building $dir"
            mvn -f $dir/pom.xml clean package -DskipTests
          done
